### ISSUE TITLE
Add multidex support from version 1.2.0-beta1

### ISSUE THREAD

**Issue by gurt-il** [DexPatcher/dexpatcher-gradle#12]
Add comparability for the new multidex option form dexpatcher-tool

Thanks a lot

**Comment by Lanchon** [comment]
lol that was fast! so there's actually people using DexPatcher besides me?? that's new... :)

well the gradle plugin has some issues:
- it was extremely complex and painful to write.
- google changes the gradle plugin all the time and breaks compatibility with mine. admittedly mine uses a lot of unpublished API, but google didn't provide any API to begin with so you do what you have to.
- there is a new internal structure in google plugin from version 1.5, so porting is hard work. on top of that there is an experimental plugin out there right now, hinting that google might switch to the new implementation any time.
- finally, the android plugin is big, big ugly beast. even if you stay with the old versions of gradle and android plugin, configuring a build based on my plugin is too complex and scares people away.

yes, my plugin could be made to support multidex. it could be ported to a newer android plugin too. but for now i have no need real for multidex in the plugin. several other things i deem more important. one such things is creating a 'standalone' plugin that does not depend on google's. it would be very easy to set up but would only support patching code, no support for manifests or resources. another is a solution to spoof signatures. yet another would be a way to apply patches directly on the phone. another is adding features to DexPatcher-tool, i would like to add many. clearly this is too much work for one person.

**Comment by gurt-il** [comment]
Hi Lanchon

I'm actually using your plugin for long time ago and it's was VERY useful.
Currently, I'm working with the original plugin on my code with BuildTools 24.
The only limitation I faced with it's the gradle plugin version (It's must be 1.2.3 version).

I understand the problem that you have mentioned, but it's my best way to develop an addon to exist application (it's very long story) with (almost) normal android studio environment.
From my point of view, only small work are needed to add the multidex support that his impotent to me due to last changes in my code that passed the 8MB limitation.
It's funny that I faces this problem first time this week, and when I went to your site I saw that you just added this ability :)

If you don't care, I will be happy to help on the development of the addon and maybe also on the development of the tool himself.

Let me know if there is any specification I should know before I starting to work on it.

Thanks
Ysrael

**Comment by Lanchon** [comment]
well if i remember correctly the gradle plugin already does some multidex stuff, like generating a multidex apk library for example. and it's absolutely great that you want to help with the project!!

but...

i think you are in luck. your use case is fairly simple if i understand you correctly: you just want to add to a unidex app, making it multidex. you might not need a new plugin for this at all.

in your case the build proceeds until dexpatcher runs, and that triggers a dexlib2 error when the pools of the dex file overflow. to make it work:
- so the pipeline can stay the same until dexpatcher runs.
- pull the gradle tools repo to get the newest dexpatcher-tool.
- all my gradle tasks allow custom arguments by extending this class:
  https://github.com/DexPatcher/dexpatcher-gradle/blob/master/src/main/groovy/lanchon/dexpatcher/gradle/tasks/CustomJavaExecTask.groovy
- you can add options to the dexpatcher task via the 'extraArgs' property. unfortunately if you add '--multi-dex' there, the build won't work because "--output" points to a file instead of a directory. and if you change the output file property, the task will fail because of this:
  https://github.com/DexPatcher/dexpatcher-gradle/blob/master/src/main/groovy/lanchon/dexpatcher/gradle/tasks/DexpatcherTask.groovy#L63
- the simplest thing you can do is modify the dexpatcher tool itself for this task: in the parser assume '--multi-dex' and use something like outputFile=outputFile.getParent() to remove the last part ('classes.dex') of the passed output file.
- now you have classes.dex and classes2.dex where the android gradle plugin expects them, so you just need to convince android plugin to build a multidex with aapt. i guess the simplest way is to enable multidex in android plugin and see what happens. otherwise, just fiddle with the aapt task to enable multidex in that one step.
- profit!

**Comment by gurt-il** [comment]
I'm actually doing more stuff in my application (I'm adding about 150 classes to the original code)  but I'll try it and let you know.

Thanks
Ysrael

**Comment by Lanchon** [comment]
hi,

multi-dex support in Android Studio is ready! :)
https://github.com/DexPatcher/dexpatcher-gradle/releases

and there's also a multi-dex sample to go with it...
https://github.com/DexPatcher/DexPatcher-gradle-samples

tell me how it goes,
later!
