### ISSUE TITLE
dexpatcher-tool-scripts functionality

### ISSUE THREAD

**Issue by samogot** [DexPatcher/dexpatcher-gradle#15]
Dexpatcher-tool-scripts is deprecated, so i think that all of it functionality is awillable as gradle tasks. Is there any tasks wich emulate dxp-setup-for-apk functionality? I mean generating smali code, decompiled java code and also java stubs?

**Comment by Lanchon** [comment]
hi! no, the gradle plugins do stuff necessary to patch. analyzing code to know what to patch is not within the scope of this plugins.

that said:

- i think the apktool decode gradle task might have a flag to turn on smali output. look the option up in my source code and try it out; smali should be spit into the build/intermediates dir somewhere.

- the gradle plugins should set things up so that IDEA is able to decompile on demand (uses fernflower i think). in the project tree, click into the libraries, source apk, and browse the source. it should also land you there if you debug or if you use the "open definition" commands.

sorry i cant give better support, im travelling. please report findings, thanks!

**Comment by Lanchon** [comment]
closed due to inactivity
