### ISSUE TITLE
error: resource 'drawable/$avd_hide_password__0' has invalid entry name '$avd_hide_password__0'. Invalid character '$avd_hide_password__0'.

### ISSUE THREAD

**Issue by Lanchon** [DexPatcher/dexpatcher-gradle#22]
# UPDATE: solution [here](https://github.com/DexPatcher/dexpatcher-gradle/issues/24)

so far this is caused by the same 6 files in all apps i've seen. i suppose these malformed files come from a google library.

these files are part of two very similar and complementary animated vector drawables:

## 1) avd_show_password
```
==> res/drawable-v21/avd_show_password.xml <==

    <?xml version="1.0" encoding="utf-8"?>
    <animated-vector android:drawable="@drawable/$avd_show_password__0"
      xmlns:android="http://schemas.android.com/apk/res/android" xmlns:aapt="http://schemas.android.com/aapt">
        <target android:name="eye_mask" android:animation="@drawable/$avd_show_password__1" />
        <target android:name="strike_through" android:animation="@drawable/$avd_show_password__2" />
    </animated-vector>


==> res/drawable-v21/$avd_show_password__0.xml <==

    <?xml version="1.0" encoding="utf-8"?>
    <vector android:height="24.0dip" android:width="24.0dip" android:viewportWidth="24.0" android:viewportHeight="24.0"
      xmlns:android="http://schemas.android.com/apk/res/android" xmlns:aapt="http://schemas.android.com/aapt">
        <path android:name="strike_through" android:pathData="@string/path_password_strike_through" android:strokeColor="@android:color/white" android:strokeWidth="1.8" android:strokeLineCap="square" />
        <group>
            <clip-path android:name="eye_mask" android:pathData="@string/path_password_eye_mask_strike_through" />
            <path android:name="eye" android:fillColor="@android:color/white" android:pathData="@string/path_password_eye" />
        </group>
    </vector>


==> res/drawable-v21/$avd_show_password__1.xml <==

    <?xml version="1.0" encoding="utf-8"?>
    <objectAnimator android:interpolator="@android:interpolator/fast_out_linear_in" android:duration="@integer/show_password_duration" android:valueFrom="@string/path_password_eye_mask_strike_through" android:valueTo="@string/path_password_eye_mask_visible" android:valueType="pathType" android:propertyName="pathData"
      xmlns:android="http://schemas.android.com/apk/res/android" xmlns:aapt="http://schemas.android.com/aapt" />


==> res/drawable-v21/$avd_show_password__2.xml <==

    <?xml version="1.0" encoding="utf-8"?>
    <objectAnimator android:interpolator="@android:interpolator/fast_out_linear_in" android:duration="@integer/show_password_duration" android:valueFrom="1" android:valueTo="0" android:propertyName="trimPathEnd"
      xmlns:android="http://schemas.android.com/apk/res/android" xmlns:aapt="http://schemas.android.com/aapt" />
```

## 2) avd_hide_password
```
==> res/drawable-v21/avd_hide_password.xml <==

    <?xml version="1.0" encoding="utf-8"?>
    <animated-vector android:drawable="@drawable/$avd_hide_password__0"
      xmlns:android="http://schemas.android.com/apk/res/android" xmlns:aapt="http://schemas.android.com/aapt">
        <target android:name="eye_mask" android:animation="@drawable/$avd_hide_password__1" />
        <target android:name="strike_through" android:animation="@drawable/$avd_hide_password__2" />
    </animated-vector>


==> res/drawable-v21/$avd_hide_password__0.xml <==

    <?xml version="1.0" encoding="utf-8"?>
    <vector android:height="24.0dip" android:width="24.0dip" android:viewportWidth="24.0" android:viewportHeight="24.0"
      xmlns:android="http://schemas.android.com/apk/res/android" xmlns:aapt="http://schemas.android.com/aapt">
        <path android:name="strike_through" android:pathData="@string/path_password_strike_through" android:strokeColor="@android:color/white" android:strokeWidth="1.8" android:trimPathEnd="0.0" android:strokeLineCap="square" />
        <group>
            <clip-path android:name="eye_mask" android:pathData="@string/path_password_eye_mask_visible" />
            <path android:name="eye" android:fillColor="@android:color/white" android:pathData="@string/path_password_eye" />
        </group>
    </vector>


==> res/drawable-v21/$avd_hide_password__1.xml <==

    <?xml version="1.0" encoding="utf-8"?>
    <objectAnimator android:interpolator="@android:interpolator/fast_out_slow_in" android:duration="@integer/hide_password_duration" android:valueFrom="@string/path_password_eye_mask_visible" android:valueTo="@string/path_password_eye_mask_strike_through" android:valueType="pathType" android:propertyName="pathData"
      xmlns:android="http://schemas.android.com/apk/res/android" xmlns:aapt="http://schemas.android.com/aapt" />


==> res/drawable-v21/$avd_hide_password__2.xml <==

    <?xml version="1.0" encoding="utf-8"?>
    <objectAnimator android:interpolator="@android:interpolator/fast_out_slow_in" android:duration="@integer/hide_password_duration" android:valueFrom="0" android:valueTo="1" android:propertyName="trimPathEnd"
      xmlns:android="http://schemas.android.com/apk/res/android" xmlns:aapt="http://schemas.android.com/aapt" />
```

the problematic `$avd_(show|hide)_password__<n>.xml` files of these composite resources are never referenced from code. they are only referenced from their corresponding main resource files `avd_(show|hide)_password.xml`.

**this allows a simple workaround: you can manually rename the problematic files to make their names valid, along with their references in the main resource files.** you can choose any names you want, but simply removing the dollar signs should be fine.

this workaround is a temporary stopgap measure. i'll be investigating ways to handle these corner cases in a more automated way.

**Comment by renaudcerrato** [comment]
Thanks! Will look into that.

**Comment by reed07** [comment]
Would you be able to elaborate on the workaround of renaming the avd files? 
At which point in the build process should this be performed--to the source apk? If so, my apk in question has some resources in a binary resources.arsc file which have references to these files. I'm not aware of an easy way to edit an arsc file.

**Comment by Lanchon** [comment]
hi,

take a look at the apk-lib sample: one suproject produces an .apklib file and another consumes it. unlink the 2 projects by feeding the second project the apklib as a file (place it in directory apklib and it will be picked up by default). once you've done that, you can edit the apklib file: the resources are decompiled there. was this clear enough?

**Comment by Lanchon** [comment]
# UPDATE: solution [here](https://github.com/DexPatcher/dexpatcher-gradle/issues/24)

**Comment by eladkarako** [comment]
<details><summary>the solution didn't worked for me</summary>
  
and I even got the most recent aapt2 binary from <a href="https://maven.google.com/web/index.html#com.android.tools.build:aapt2:7.2.0-alpha04-7832930">https://maven.google.com/web/index.html#com.android.tools.build:aapt2:7.2.0-alpha04-7832930</a>,  
copied the (only) x86 exe, to make it suitable for the i386 and x64 directory tree,  
and repacked it (and I even went to make a nightly build of apktool in-which I've replaced the binaries with the newest ones, and used the regular and <code>_64</code> suffix).

<img src="https://user-images.githubusercontent.com/415238/141610713-36d4f8c9-839e-4163-9109-c5377f869860.png" />
</details>

<hr/>

but it didn't matter too much since I prefer the manual fix anyway.

(and it is also suitable for <strong>apktool users</strong> as well that came here through google...)

<hr/>

<ol>
<li>
rename files:
<img title="rename files (remove dollar sign prefix)" src="https://user-images.githubusercontent.com/415238/141608196-42fb1791-6d6e-4e9e-8908-f7fd849e0e9b.png" />
<ol type="1">
<li>
  <code>/res/drawable-v21/$avd_hide_password__0.xml</code>
  to:
  <code>/res/drawable-v21/avd_hide_password__0.xml</code>
</li>
<li>
  <code>/res/drawable-v21/$avd_hide_password__1.xml</code>
  to:
  <code>/res/drawable-v21/avd_hide_password__1.xml</code>
</li>
<li>
  <code>/res/drawable-v21/$avd_hide_password__2.xml</code>
  to:
  <code>/res/drawable-v21/avd_hide_password__2.xml</code>
</li>
<li>
  <code>/res/drawable-v21/$avd_show_password__0.xml</code>
  to:
  <code>/res/drawable-v21/avd_show_password__0.xml</code>
</li>
<li>
  <code>/res/drawable-v21/$avd_show_password__1.xml</code>
  to:
  <code>/res/drawable-v21/avd_show_password__1.xml</code>
</li>
<li>
  <code>/res/drawable-v21/$avd_show_password__2.xml</code>
  to:
  <code>/res/drawable-v21/avd_show_password__2.xml</code>
</li>
</ol>
</li>
<li>
fix references to new file-names inside other files:
<img src="https://user-images.githubusercontent.com/415238/141608627-65b5b392-7b23-41bc-ad22-8a2c07f8518f.png" />

use a proper Notepad.. (not Windows' one!)

<ol type="1">
<li>
  open <code>/res/drawable-v21/avd_hide_password.xml</code>

  remove every <code>$</code>, to suite the actual, new, file-names:

  <img src="https://user-images.githubusercontent.com/415238/141608663-2f5edb01-1fd6-4cc5-8cf5-3e307f752cae.png" />

  change:

```xml
<?xml version="1.0" encoding="utf-8"?>
<animated-vector android:drawable="@drawable/$avd_hide_password__0"
  xmlns:android="http://schemas.android.com/apk/res/android" xmlns:aapt="http://schemas.android.com/aapt">
    <target android:name="eye_mask" android:animation="@drawable/$avd_hide_password__1" />
    <target android:name="strike_through" android:animation="@drawable/$avd_hide_password__2" />
</animated-vector>
```

  to:

```xml
<?xml version="1.0" encoding="utf-8"?>
<animated-vector android:drawable="@drawable/avd_hide_password__0"
  xmlns:android="http://schemas.android.com/apk/res/android" xmlns:aapt="http://schemas.android.com/aapt">
    <target android:name="eye_mask" android:animation="@drawable/avd_hide_password__1" />
    <target android:name="strike_through" android:animation="@drawable/avd_hide_password__2" />
</animated-vector>
```

</li>

<li>
  open <code>/res/drawable-v21/avd_show_password.xml</code>

  remove every <code>$</code>, to suite the actual, new, file-names:

  <img src="https://user-images.githubusercontent.com/415238/141608830-2aef514f-ec19-438e-b275-9f141a477191.png" />

  change:

```xml
<?xml version="1.0" encoding="utf-8"?>
<animated-vector android:drawable="@drawable/$avd_show_password__0"
  xmlns:android="http://schemas.android.com/apk/res/android" xmlns:aapt="http://schemas.android.com/aapt">
    <target android:name="eye_mask" android:animation="@drawable/$avd_show_password__1" />
    <target android:name="strike_through" android:animation="@drawable/$avd_show_password__2" />
</animated-vector>
```

  to:

```xml
<?xml version="1.0" encoding="utf-8"?>
<animated-vector android:drawable="@drawable/avd_show_password__0"
  xmlns:android="http://schemas.android.com/apk/res/android" xmlns:aapt="http://schemas.android.com/aapt">
    <target android:name="eye_mask" android:animation="@drawable/avd_show_password__1" />
    <target android:name="strike_through" android:animation="@drawable/avd_show_password__2" />
</animated-vector>
```

</li>
<li>
  open <code>/res/values/public.xml</code>

  <img src="https://user-images.githubusercontent.com/415238/141609818-1f0f3ce4-57a2-44c8-9891-598bc294fec0.png">

  use <kbd>CTRL</kbd>+<kbd>F</kbd>, to quickly search-for <code>$avd_</code>, and fix all those reference (remove the <code>$</code> prefix),
  just like you've done before...

  change:

  <img src="https://user-images.githubusercontent.com/415238/141609512-52b78a8e-026b-453d-af9f-80afcaad08fa.png" />

  to:

  <img src="https://user-images.githubusercontent.com/415238/141609583-82889818-179c-412e-891f-d18b66bc8be4.png" />

  <hr/>

  if you're already in that file, do a quick search for <code>$</code> character, you should not find any.
</li>

</ol>

</li>

</ol>

**Comment by Lanchon** [comment]
@eladkarako you are posting on an obsolete thread. which solution did not work? the linked solution is also obsolete. the proper solution is here: https://github.com/DexPatcher/dexpatcher-gradle/releases/tag/v2.0.0

> the solution didn't worked for me
and I even got the most recent aapt2 binary from https://maven.google.com/...

the solution works. if you are using binaries for google then **you are not following the instructions**. go back and reread the howto.

if you have an issue, please don't resurrect dead obsolete issues: create a new thread describing your particular issue.
