### ISSUE TITLE
Could not initialize class lanchon.dexpatcher.gradle.helpers.Aapt2MavenUtilsHelper

### ISSUE THREAD

**Issue by oooooooko** [DexPatcher/dexpatcher-gradle#41]
![image](https://github.com/DexPatcher/dexpatcher-gradle/assets/48895716/4508bdf6-01b1-41e9-83ce-80f5d74df76b)

**Comment by Lanchon** [comment]
i need the full build log. use ./gradlew command line to build and capture.

**Comment by ffdsss** [comment]
> ./gradlew 命令

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'D:\devRes\android\PatchX\app\build.gradle' line: 29

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not initialize class lanchon.dexpatcher.gradle.helpers.Aapt2MavenUtilsHelper

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':app'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 783ms

**Comment by Lanchon** [comment]
at least run with build with --scan and post the link. could not initialize means an exception in the static initializer was thrown. there is a root cause exception that i cant see there.

**Comment by oooooooko** [comment]
> at least run with build with --scan and post the link. could not initialize means an exception in the static initializer was thrown. there is a root cause exception that i cant see there.

This error will be reported when the AGP version is 4.2.0+. I lower the AGP version to 4.0.1 and this error will not be reported. But there will be the problem of Android resource linking failed

![image](https://github.com/DexPatcher/dexpatcher-gradle/assets/48895716/b3b0396e-2c41-40a7-b3c1-6d7c8e490190)

This is an error from AGP 4.0.1

[log.txt](https://github.com/DexPatcher/dexpatcher-gradle/files/11954728/log.txt)

**Comment by Lanchon** [comment]
> ´AAPT: unknown option '--no-proguard-location-reference'.´

from https://github.com/DexPatcher/dexpatcher-gradle/releases:

- Apktool is running late on updates, and the AAPT2 binaries shipped with latest Apktool (v2.4.1) are not compatible with the Android Gradle plugin v3.6. Until the Apktool project updates their AAPT2 binaries, builds will fail if `useAapt2BundledWithApktool` is enabled and it will not be possible to patch apps having invalid resources.

  Note that incompatibilities mostly stem from new ProGuard options in AAPT2 which are emitted even if ProGuard processing is disabled. An adapter script that filters out these options could be used to make the newer plugins work with older versions of AAPT2. The script would be configured as the AAPT2 executable using the existing DexPatcher-gradle infrastructure for AAPT2 executable selection.

  Also note that Android seems to be moving towards a pure JVM build ecosystem, which would entail phasing out AAPT2. This can be seen in the code of the Android Gradle plugin v4.0. How this change will impact the processing of apps with invalid resources cannot be predicted at this time.

----

i dont know the versions of the software you are using because you dont publish your project.

i need to know versions of:
- gradle
- AGP
- dexpatcher-gradle
- dexpatcher-tool
- apktool

note that [release notes](https://github.com/DexPatcher/dexpatcher-gradle/releases) for each dxp-gradle version gives you compatible version ranges for AGP and gradle. also the samples for each dxp-gradle linked from their release notes show examples of configurations that work.

**Comment by Lanchon** [comment]
also note that the latest released dxp-gradle is: https://github.com/DexPatcher/dexpatcher-gradle/releases/tag/v2.0.0

newers are pre-releases as shown in release notes.

also check latest published version here: https://plugins.gradle.org/search?term=dexpatcher

as stated in v2.0.0 release notes you should be using:

- Android Gradle plugin v3.4.2.
  Note: Android Gradle plugin imposes [Gradle version limitations](https://developer.android.com/studio/releases/gradle-plugin#updating-gradle).
- Gradle v5.1.1 (though v5.1.1 through v5.6.4 *should* work).

you are using AGP 4, so nothing will work. you have to read the docs!

**Comment by oooooooko** [comment]
> also note that the latest released dxp-gradle is: https://github.com/DexPatcher/dexpatcher-gradle/releases/tag/v2.0.0
> 
> newers are pre-releases as shown in release notes.
> 
> also check latest published version here: https://plugins.gradle.org/search?term=dexpatcher
> 
> as stated in v2.0.0 release notes you should be using:
> 
> * Android Gradle plugin v3.4.2.
>   Note: Android Gradle plugin imposes [Gradle version limitations](https://developer.android.com/studio/releases/gradle-plugin#updating-gradle).
> * Gradle v5.1.1 (though v5.1.1 through v5.6.4 _should_ work).
> 
> you are using AGP 4, so nothing will work. you have to read the docs!

Thank you very much, I changed the version as you asked. After rebuilding, it prompts "AAPT: error: duplicate value for resource 'attr/navigationMode' with config"

![image](https://github.com/DexPatcher/dexpatcher-gradle/assets/48895716/e26697c9-b48d-4b3b-b1f6-731df4670432)

![image](https://github.com/DexPatcher/dexpatcher-gradle/assets/48895716/27df69d9-972f-4b70-af2a-ca32a8e95bca)

![image](https://github.com/DexPatcher/dexpatcher-gradle/assets/48895716/08a5c92f-3749-4a95-9221-6012bb11763e)

![image](https://github.com/DexPatcher/dexpatcher-gradle/assets/48895716/e39cdcbf-2fe4-4ba3-b1b7-57a6159fe069)

**Comment by Lanchon** [comment]
i recommend you use dxp-tool v1.8.0-beta1.

why are you using apktool 2.4? 2.7.0 is the current version.

i can't help you because you are not publishing the complete project. but it seems your project wants to add a value for 'attr/navigationMode'? or maybe apktool is too old? i don't know, i dont have the project.

**Comment by oooooooko** [comment]
> i recommend you use dxp-tool v1.8.0-beta1.
> 
> why are you using apktool 2.4? 2.7.0 is the current version.
> 
> i can't help you because you are not publishing the complete project. but it seems your project wants to add a value for 'attr/navigationMode'? or maybe apktool is too old? i don't know, i dont have the project.

The version used in your sample project is apktool 2.4, so I also used this one. I have uploaded my local code, and this is the link:[ https://github.com/ffdsss/patcher-test](url)

**Comment by oooooooko** [comment]
It has been solved, thank you

**Comment by Lanchon** [comment]
ok, sorry i didn't have time to look at it yet, but im glad you could solve it by yourself :+1: :+1:
